- package.json
- src/single-spa-react.js
When I wrote this library, I wasn't aware that `ReactDOM.render` could potentially be asynchronous and provided a callback API for when it finished mounting an application. See https://facebook.github.io/react/docs/react-dom.html#render.
This should be totally backwards compatible, and I tested it with communications-ui and it worked great.
> Using ReactDOM's builtin callback for knowing when mount is finished

- src/single-spa-react.js
It would be great if we could pass the instantiated component down to the middle ware. This is especially useful since this (https://github.com/CanopyTax/single-spa/pull/156) PR has been merged. Here is a simple use case for this:
```js
// root-application.js
singleSpa.registerApplication('app1', () =>  {}, () => {}, {authToken: "d83jD63UdZ6RS6f70D0"});
```
```js
// app.js
export function mount(props) {
return reactLifecycles.mount(props).then((rootComponent) => {
rootComponent.setAuthToken(props.customProps.authToken);
});
}
```
```js
// root.component.js
export default class Root extends React.Component {
state = {authToken: ''};
setAuthToken(authToken) {
this.setState(() => ({
authToken: authToken
}));
}
render() {
return (
<div>
{this.state.authToken}
</div>
);
}
}
```
Our actual use …
> The lifecycle method 'mount' does receive the root component instance now

- README.md
- package.json
- src/single-spa-react.js
- src/single-spa-react.test.js
Mainly opens the door for concurrent (async) React, and also hydrate in case anyone has that need as well. 
Potentially fixes #41
> Support other render types

- src/single-spa-react.js
If you use an arrow function component as your rootComponent for single-spa, and you do not configure babel to transpile to a named function, single-spa will crash when attempting to access the prototype's componentDidCatch.
`if (!opts.rootComponent.prototype.componentDidCatch)`
The easiest solution is to wrap in CanopyReactErrorBoundary: 
`rootComponent: CanopyReactErrorBoundary({ featureName: my-component' })(MyComponent),`
To let the developer know, and to prevent the crash, I've added a second check to see if the prototype exists.  If not, a warning is sent to the console.
> handle components that do not have a prototype

- package.json
- src/single-spa-react.js
I confirmed that this change works by testing a service and having it render with both `createRoot` and `createBlockingRoot` along with the latest experimental build of react.
API reference https://reactjs.org/docs/concurrent-mode-reference.html#concurrent-mode
> adding option for createBlockingRoot render, part of new concurrent mode

- src/single-spa-react.js
I have a use case where I'd like to load other assets in parallel with my root component and use the props in the loading logic, for example translations using a `locale` prop:
```js
// my-parcel
import React from 'react'
import singleSpaReact from 'single-spa-react'
export default singleSpaReact({
React,
ReactDOM,
loadRootComponent: ({ locale }) => Promise.all([
import('./MyComponent'),
fetch(`/my-translations/${locale}.json`)
]).then(([ MyComponent, myTranslations ]) => (props) => (
<MyComponent {...props} translations={myTranslations}/>
)
)
})
// my app
import Parcel from 'single-spa-react/parcel'
import parcelConfig from './my-parcel'
export default () => <Parcel config={parcelConfig} locale="en"/>
```
> Pass props to loadRootComponent

- src/single-spa-react.js
- src/single-spa-react.test.js
Making it possible to reuse the same parcel config for multiple parcels This should fix #67
> fixing #67

- .babelrc
- package.json
- rollup.config.js
- src/parcel.js
- src/single-spa-react.js
- src/single-spa-react.test.js
- yarn.lock
Resolves #74. In all of this I ended up switching the build from babel cli to rollup + terser. The bundle size has gone down from 11kb to 5kb, but there are some weird things about it (see below)
> Switching to rollup and adding errorBoundary opt

- .npmignore
- package.json
Using `files` in the package.json is easier than npmignore to get the files you want since it's an include list instead of an exclude list. This reduced the tarball created by `npm pack` from 24kb to 15kb
> Decreasing tarball size published to npm.

- .babelrc
- package.json
- src/single-spa-react.js
- src/single-spa-react.test.js
- yarn.lock
See #82. The root cause of the problem here is that when we originally implemented parcels, the custom props were passed as a `customProps` property on the overall props object. After some feedback, we moved them to just be merged as top level properties. Then we changed single-spa-react to "work both ways." However, this caused confusion and a bug that was reported in #82. The older behavior for customProps was removed in https://github.com/single-spa/single-spa/releases/tag/v4.0.0-beta.6 and never made it into a stable release of single-spa. So I think it's fine to remove this behavior in single-spa-react without considering it a breaking change.
> Fixing issue with customProps prop. Resolves #82.

- src/single-spa-react.js
- src/single-spa-react.test.js
createBlockingRoot is now implemented twice, after #94. This PR cleans that up.
> Removing dead code and adding tests

- src/single-spa-react.test-d.ts
- types/single-spa-react.d.ts
This will add type definitions for the exported SingleSpaContext.
> Add SingleSpaContext type definition.

- src/single-spa-react.js
See #105. Rollup incorrectly is replacing all instances of `SingleSpaContext` with `null` inside of the output `parcel.js` bundle. We set the value inside of a function, which is apparently beyond what rollup's replacement algorithm can detect.
Adding the try/catch is a way of letting rollup know that the value isn't null, without setting it to a dummy value that could break things for users who do use `SingleSpaContext` as an API and expect it to either be null or a valid react context.
I'm open to other suggestions about how to fix this.
> Fix bug with Parcels relying on SingleSpaContext. Resolves #105.

- jest.config.js
- package.json
- pnpm-lock.yaml
- rollup.config.js
- src/parcel.js
See #105.
The problem was that single-spa-react.js was being bundled into parcel.js. So you'd end up with two instances of single-spa-react.js - the intentional one and the accidental one. The accidental one would never have the SingleSpaContext set correctly.
See https://cdn.jsdelivr.net/npm/single-spa-react@4.1.1/lib/esm/parcel.js and search for `createContext`. Note that it's present, even though createContext is only in single-spa-react.js and not parcel.js in the source code.
The fix is to correct the rollup externals when bundling parcel.js
> Avoid bundling single-spa-react into Parcel component. See #105.

- types/single-spa-react.d.ts
Both the [documentation](https://single-spa.js.org/docs/ecosystem-react/) and [source code](https://github.com/single-spa/single-spa-react/blob/07e9272d83655fbe8e7d2269b143a897da4e5fa6/src/single-spa-react.js#L98) show that loadRootComponent method accepts one parameter which contains the single-spa props.
> types: add props to loadRootComponent

- src/single-spa-react.js
- src/single-spa-react.test.cjs
- types/single-spa-react.d.ts
Added the possibility to use `renderType` as a function. This enables apps to determine at runtime if they should use e.g., `hydrate` or `render` which does change for some applications (for example server-side rendered ones).
Setting `hydrate` as a constant for SSR apps produce a bug whenever the users entry-point to the site is not server-side rendered, as normal routing towards this app will not hit the server and the DOM will not have SSR content when the app bootstraps, which in turn produces an error message similar to this when reactdom.hydrate() is called (taken from isomorphic.microfrontends.app):
```
Warning: Expected server HTML to contain a matching <div> in <div>.
in div (created by Pr)
in Pr (created by _r)
in t (created by t)
in t (created by _r)
in _r (created by …
```
> Add option to use a function as renderType

- src/single-spa-react.js
- src/single-spa-react.test.cjs
See #134. The issue was that `SingleSpaRoot` was being recreated each time that `getElementToRender` was called, which meant that `oldElement.type === newElement.type` was false during React's reconciliation algorithm, causing a remount.
> Fix parcel updates causing unmount + remount. Resolves #134.

- package.json
- pnpm-lock.yaml
Resolves #133. I guess the browserslist configs are used not at a per-project level rather than just globally (which is how I thought of them), so moving our config from a devDependency to dependency makes sure it's available for all users of single-spa-react who are compiling with babel
> Move browserslist-config-single-spa to "dependencies". Resolves #133

- src/single-spa-react.js
- src/single-spa-react.test.cjs
The root object currently only allows a single `unmountFinished` promise at a time. Multiple parcels unmounting at the same time leads to most promises orphaned and not resolving, throwing console warnings.
This PR uses the parcel name to differentiate unmount promises.
Before:
After:
> Fix multi-parcel unmount resolving

- .github/workflows/build-test.yml
After validating that this is [working as intended in CI](https://github.com/single-spa/single-spa-react/actions/runs/4237867778/jobs/7364303480), I'm enabling automated publishing through this PR. I'll also be marking it as a patch release and fixing the release notes to remove the mention to React 18 support that landed with v5.
> Enable publishing

- src/single-spa-react.js
When a parcel is mounted it checks if `errorBoundary` is set or it implements the `componentDidCatch` function, if those are not available it will log a warning to the console. This warning is always logged when you use the `errorBoundaryClass` property. 
It is possible to work around this by setting `suppressComponentDidCatchWarning` but that feels a bit weird, so this PR fixes this issue by include an additional check if the `errorBoundaryClass` is set
> Do not log a warning when the `errorBoundaryClass` is provided

- .changeset/stale-readers-pull.md
- .github/workflows/build-test-release.yml
Fixing a small typo in the node version of the release workflow. This harmonizes the node version of the two workflows.
> Fix node version for release workflow

- .changeset/fifty-bats-stare.md
- src/single-spa-react.js
> Change default renderType based on React version. Resolves #202

- .changeset/nasty-gifts-check.md
- package.json
- pnpm-lock.yaml
- src/parcel.js
- src/parcel.test.js
[StrictMode](https://react.dev/reference/react/StrictMode) in React 18 renders a component an extra time where the component is unmounted and mounted again. This sets the `unmounted` value to `true` which prevent to component from actually mounting.
Fixes #160
> Fixed an issue with mounting a parcel when StrictMode is enabled
